"""Optimized models with joined loading, cascade, and formatted_time

Revision ID: a87bb91d0dca
Revises: 
Create Date: 2025-11-02 01:16:15.547011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a87bb91d0dca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slot', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_doctor_slot', ['doctor_id', 'date', 'start_time'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slot', schema=None) as batch_op:
        batch_op.drop_constraint('uq_doctor_slot', type_='unique')

    # ### end Alembic commands ###
